// client-react/src/App.tsx
import React, { useEffect, useState } from 'react';
import './styles/global.css';
import NavBar from './components/NavBar';
import { seedTree } from './control/Yggdrasil';
import { BrandIcon } from './components/BrandIcon';
import Icon from './components/Icon';
import Code from './components/Code';
import Home from './pages/Home';
import Examples from './pages/Examples';
import Statistics from './pages/Statistics';
import Diagnostics from './pages/Diagnostics';
import initSemanticTabsDirty from './components/SemanticTab';
import Footer from './components/Footer';

function App() {
  const [yggdrasil, _] = useState(seedTree({
    data: "https://api.birchy.dev",
    profiler: "https://coffee.birchy.dev/",
    crash: "https://crash.birchy.dev/",
    trace: 'https://trace.birchy.dev'
  }, {
    link: "",
    img: ""
  }));

  const [nav, setNav] = useState('nav::home');

  const stylesheets = [
    'semantic/semantic.min.css',
    'semantic/components/container.min.css',
    'semantic/components/grid.min.css',
    'semantic/components/header.min.css',
    'semantic/components/menu.min.css',
    'semantic/components/modal.min.css',
    'semantic/components/tab.min.css',
    'highlight/dracula.css',
  ].map(style => (<link key={style} rel='stylesheet' href={style} />));

  useEffect(() => initSemanticTabsDirty('.ui.menu .item'));

  return (
    <div className="kafei">
      {stylesheets}
      <NavBar
        defaultItem={nav}
        callback={setNav}
        internalLinks={yggdrasil.menu.links}
        externalLinks={yggdrasil.menu.externals}
      />
      <BrandIcon icon='facebook' />
      <Icon icon='box' size={48} foreground='white' />
      <Code language="cpp">
        int main()
          return 0;
      </Code>

      <Home />
      <Examples />
      <Statistics />
      <Diagnostics data={yggdrasil.diagnostics} />

      <Footer source={{
          link: 'https://github.com/hbirchtree/kafei-py'
        }}
      />
    </div>
  );
}

export default App;

// client/src/App.svelte
<script>
    import Navbar from './Navbar.svelte';
    import Home from './Home.svelte';
    import Statistics from './Statistics.svelte';
    import Footer from './Footer.svelte';
    import * as j from 'jquery';

    import {onMount} from 'svelte';
	
    export let navLinks = [
            {name: "Home", target: "nav::home"},
            {name: "Examples", target: "nav::examples"},
            {name: "Statistics", target: "nav::stats"},
            {name: "Diagnostics", target: "nav::diag"}
    ];
    export let github = {link: "https://github.com/hbirchtree", img: "https://avatars3.githubusercontent.com/u/6828070?s=80&v=4"};
    export let endpoints = {
            data: "https://api.birchy.dev",
            profiler: "https://coffee.birchy.dev",
            crash: "https://crash.birchy.dev"
    };

    onMount(async () => {
        window.$('.ui.menu .item').tab();
    });
</script>

<link rel="stylesheet" type="text/css" href="semantic/semantic.min.css">
<link rel="stylesheet" type="text/css" href="semantic/components/container.min.css">
<link rel="stylesheet" type="text/css" href="semantic/components/header.min.css">
<link rel="stylesheet" type="text/css" href="semantic/components/menu.min.css">
<link rel="stylesheet" type="text/css" href="semantic/components/modal.min.css">
<link rel="stylesheet" type="text/css" href="semantic/components/tab.min.css">

<Navbar links={navLinks} github={github}/>

<div data-tab="nav::home" class="ui inverted text tab segment active">
    <Home github={github} endpoints={endpoints}/>
</div>
<div data-tab="nav::examples" class="ui inverted text tab segment">
    Examples
</div>
<div data-tab="nav::stats" class="ui inverted text tab segment">
    <Statistics endpoints={endpoints}/>
</div>
<div data-tab="nav::diag" class="ui inverted text tab segment">
    Diagnostics
</div>


<Footer/>

<style>
    div.segment {
        max-width: 60em;
        margin-left: auto;
        margin-right: auto;
    }
</style>

<link href="https://fonts.googleapis.com/css?family=Ubuntu+Mono:400,400i,700&amp;subset=latin-ext" rel="stylesheet">
