// client/src/Button.svelte
<script lang="ts">
    import Icon from './Icon.svelte';
    import type { Color } from './Types';

    export let icon: string;
    export let label: string;
    export let color: Color = "blue";
    export let onclick: () => Promise<void> = async () => {};
    export let margin: string = '1em';
</script>

<button on:click={onclick} class="ui {color} button flex-centered-important" style="margin: {margin};">
    <Icon icon={icon} /> {label}
</button>

// client-react/src/components/Button.tsx
import React from 'react';
import { Color } from '../control/Types';
import '../styles/Button.scss';
import Icon from './Icon';

interface Props {
    action?: () => void;
    color?: Color;
    margin?: string;
    label: string;
    icon?: string;
}

export default function Button(props: Props) {
    return (
        <button 
            disabled={!props.action}
            onClick={props.action}
            className={`ui ${props.color ? props.color : 'blue'} button flex-centered-important`}
            style={{margin: props.margin ? props.margin : '1em'}}
        >
            {props.icon && (<Icon icon={props.icon} />)} {props.label}
        </button>
    );
}
