// client/src/Footer.svelte
<script>
    import Icon from './Icon.svelte';
    import {onMount} from 'svelte';
    onMount(() => {
        feather.replace();
    });
</script>

<style>
    div {
        background-color: #191970 !important;
    }
</style>

<div class="ui inverted vertical footer segment centered flex-centered">
    <span>source can be found over at</span>
    <a href="https://github.com/hbirchtree/kafei-py" class="flex-centered">
        <Icon icon="github" rounded=true />
        <span>github</span>
    </a>
</div>

// client-react/src/components/Footer.tsx
import React from 'react';
import Icon from './Icon';
import '../styles/Footer.scss';
import { GithubRepository } from '../control/Types';

interface Props {
    source: GithubRepository;
}

export default function Footer(props: Props) {
    return (
        <div
            className="ui inverted vertical footer segment centered flex-centered"
        >
            <span>source can be found over at</span>
            <a href={props.source.link} className="flex-centered">
                <Icon icon='github' rounded={true} />
                <span>github</span>
            </a>
        </div>
    );
}
